dist: bionic
language: ruby
jobs:
  include:
    - rvm: 2.7
      gemfile: Gemfile
    - rvm: 2.6
      gemfile: test/gemfiles/mysql2.gemfile
      services:
        - mysql
      before_install:
        - mysqladmin create delete_in_batches_test
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
